In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

In [3]:
PYTHON_PATHS = ["../.."]
import sys
for path in PYTHON_PATHS:
    if path not in sys.path:
        sys.path.append(path)

In [6]:
from imap.utils.utils import (
    generate_image_meshgrid, 
    get_ji_pixels_from_meshgrid, 
    get_ij_pixels_from_meshgrid)


In [7]:
width = 640
height = 480

x, y = generate_image_meshgrid(width, height)
print(x)
print(y)

[[  0   1   2 ... 637 638 639]
 [  0   1   2 ... 637 638 639]
 [  0   1   2 ... 637 638 639]
 ...
 [  0   1   2 ... 637 638 639]
 [  0   1   2 ... 637 638 639]
 [  0   1   2 ... 637 638 639]]
[[  0   0   0 ...   0   0   0]
 [  1   1   1 ...   1   1   1]
 [  2   2   2 ...   2   2   2]
 ...
 [477 477 477 ... 477 477 477]
 [478 478 478 ... 478 478 478]
 [479 479 479 ... 479 479 479]]


In [136]:
coordinates = get_ij_pixels_from_meshgrid(x, y)
coordinates

array([[  0,   0],
       [  0,   1],
       [  0,   2],
       ...,
       [479, 637],
       [479, 638],
       [479, 639]])

In [8]:
get_ij_pixels_from_meshgrid(x, y)

array([[  0,   0],
       [  0,   1],
       [  0,   2],
       ...,
       [479, 637],
       [479, 638],
       [479, 639]])

In [9]:
get_ji_pixels_from_meshgrid(x, y)

array([[  0,   0],
       [  1,   0],
       [  2,   0],
       ...,
       [637, 479],
       [638, 479],
       [639, 479]])

In [8]:
gen = np.random.default_rng() 


In [12]:
limited_coordinates = coordinates[:5]
limited_coordinates

array([[0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [0, 4]])

In [37]:
p = np.ones(coordinates.shape[0]) / coordinates.shape[0]

In [38]:
p

array([3.25520833e-06, 3.25520833e-06, 3.25520833e-06, ...,
       3.25520833e-06, 3.25520833e-06, 3.25520833e-06])

In [138]:
%%time
pixels = gen.choice(coordinates, 200, axis=0, p=p, shuffle=False)
pixels

CPU times: user 3.85 ms, sys: 0 ns, total: 3.85 ms
Wall time: 3.48 ms


array([[140, 544],
       [287, 187],
       [391, 438],
       [  7, 269],
       [293,  48],
       [230, 620],
       [ 95, 259],
       [154,  64],
       [370, 468],
       [134,  92],
       [320, 630],
       [ 88, 503],
       [109, 629],
       [136, 472],
       [ 98, 171],
       [128, 196],
       [376, 344],
       [  1, 400],
       [218, 532],
       [127, 453],
       [ 96,  70],
       [236, 393],
       [383, 428],
       [243, 124],
       [195, 258],
       [  5, 264],
       [ 47, 203],
       [459, 192],
       [132, 401],
       [ 23, 338],
       [151, 541],
       [459,  61],
       [474, 313],
       [230,  78],
       [151,  19],
       [411, 600],
       [237, 631],
       [347, 307],
       [379, 576],
       [ 75, 546],
       [380, 629],
       [178, 484],
       [364, 585],
       [ 47,  69],
       [285,   2],
       [ 32,  71],
       [427,  89],
       [137, 374],
       [251, 243],
       [456, 493],
       [ 26, 349],
       [179, 304],
       [276,

In [140]:
i = pixels[:, 0]
i

array([140, 287, 391,   7, 293, 230,  95, 154, 370, 134, 320,  88, 109,
       136,  98, 128, 376,   1, 218, 127,  96, 236, 383, 243, 195,   5,
        47, 459, 132,  23, 151, 459, 474, 230, 151, 411, 237, 347, 379,
        75, 380, 178, 364,  47, 285,  32, 427, 137, 251, 456,  26, 179,
       276, 416, 168, 193, 321, 196,  55, 113,  26, 387, 325, 339, 340,
       153, 173, 206, 298, 379, 311, 147, 478, 326, 429, 189, 328, 133,
       305, 115,  41, 181, 442, 350, 343, 168,  31, 304, 177, 446, 152,
        82, 388, 448, 274, 465, 173, 271,  82,  60, 187, 160, 345, 148,
        90, 432, 402, 217, 129, 115, 366,  43, 459, 357, 291, 414,  28,
       266, 355, 264, 418, 250, 268, 394, 179, 140,  63,  47, 183, 320,
       412, 437, 412, 294, 425, 294, 474,  15,  20, 428,  61, 435, 190,
       191, 135, 345, 141,  33, 373,  77,  22,   7,  48, 225, 271, 371,
       287, 139,  51, 167, 323, 114, 310, 206, 408, 424, 439, 254, 225,
       145, 419, 111, 353,  28, 168, 471, 424,  80, 198,  11, 16

In [142]:
j = pixels[:, 1]
j

array([544, 187, 438, 269,  48, 620, 259,  64, 468,  92, 630, 503, 629,
       472, 171, 196, 344, 400, 532, 453,  70, 393, 428, 124, 258, 264,
       203, 192, 401, 338, 541,  61, 313,  78,  19, 600, 631, 307, 576,
       546, 629, 484, 585,  69,   2,  71,  89, 374, 243, 493, 349, 304,
        37, 473, 533, 617,  31, 394, 527, 248, 130, 185, 247, 117,  77,
       530, 398,  36, 249, 196, 358, 498, 134, 220, 363, 271, 594, 396,
       257, 518, 334, 105, 231, 316, 166, 162, 480, 408, 187, 565,  92,
       576, 620,  12, 215, 430, 104, 378, 319, 286, 268, 206, 419, 519,
       553, 507, 531, 432, 472, 506,  36,   8, 324, 482, 286, 442,  51,
       105, 597,  51, 599, 629, 579,  16, 371, 153, 460, 416, 554, 229,
       284, 333, 384, 309, 241, 565, 345,  71, 206, 290, 248, 336,  32,
       558, 374, 474, 595,  25, 447, 489, 195, 134, 455, 371, 414, 343,
       472, 339, 293, 162, 256, 613, 512, 448, 157, 430, 310, 272, 306,
       327, 474, 498,  45, 283, 429,  45,  98, 504,  63, 336, 16

In [145]:
np.array([j, i], dtype=np.float32).T

array([[544., 140.],
       [187., 287.],
       [438., 391.],
       [269.,   7.],
       [ 48., 293.],
       [620., 230.],
       [259.,  95.],
       [ 64., 154.],
       [468., 370.],
       [ 92., 134.],
       [630., 320.],
       [503.,  88.],
       [629., 109.],
       [472., 136.],
       [171.,  98.],
       [196., 128.],
       [344., 376.],
       [400.,   1.],
       [532., 218.],
       [453., 127.],
       [ 70.,  96.],
       [393., 236.],
       [428., 383.],
       [124., 243.],
       [258., 195.],
       [264.,   5.],
       [203.,  47.],
       [192., 459.],
       [401., 132.],
       [338.,  23.],
       [541., 151.],
       [ 61., 459.],
       [313., 474.],
       [ 78., 230.],
       [ 19., 151.],
       [600., 411.],
       [631., 237.],
       [307., 347.],
       [576., 379.],
       [546.,  75.],
       [629., 380.],
       [484., 178.],
       [585., 364.],
       [ 69.,  47.],
       [  2., 285.],
       [ 71.,  32.],
       [ 89., 427.],
       [374.,

In [143]:
pixels.T

array([[140, 287, 391,   7, 293, 230,  95, 154, 370, 134, 320,  88, 109,
        136,  98, 128, 376,   1, 218, 127,  96, 236, 383, 243, 195,   5,
         47, 459, 132,  23, 151, 459, 474, 230, 151, 411, 237, 347, 379,
         75, 380, 178, 364,  47, 285,  32, 427, 137, 251, 456,  26, 179,
        276, 416, 168, 193, 321, 196,  55, 113,  26, 387, 325, 339, 340,
        153, 173, 206, 298, 379, 311, 147, 478, 326, 429, 189, 328, 133,
        305, 115,  41, 181, 442, 350, 343, 168,  31, 304, 177, 446, 152,
         82, 388, 448, 274, 465, 173, 271,  82,  60, 187, 160, 345, 148,
         90, 432, 402, 217, 129, 115, 366,  43, 459, 357, 291, 414,  28,
        266, 355, 264, 418, 250, 268, 394, 179, 140,  63,  47, 183, 320,
        412, 437, 412, 294, 425, 294, 474,  15,  20, 428,  61, 435, 190,
        191, 135, 345, 141,  33, 373,  77,  22,   7,  48, 225, 271, 371,
        287, 139,  51, 167, 323, 114, 310, 206, 408, 424, 439, 254, 225,
        145, 419, 111, 353,  28, 168, 471, 424,  80